# check if tests succeed
sudo: required
language: python
python:
  - "3.5"

services:
  - docker

before_install:
  - printenv | grep -E '^TRAVIS_' > .env
  - docker build -t testdocker .
  - docker network create -d bridge mongodb-net
  - docker run -d --net=mongodb-net --name=mongodb mongo:3.4

install:
  - docker run --net=mongodb-net testdocker /bin/sh -c "cd /root/memeshark; python3.5 setup.py install"

script:
  - docker run --net=mongodb-net testdocker /bin/sh -c "cd /root/memeshark; python3.5 setup.py test"

after_success:
  - docker run --env-file .env --net=mongodb-net testdocker /bin/sh -c "cd /root/memeshark; make deploy > /dev/null"